version: "3.8"
services:
  dev-db:
    image: postgres:16.2
    container_name: prisma-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1se2cret3
      POSTGRES_DB: prisma-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
